// This guess the number game is a short TypeScript/Node.js project that allows the user to guess the number generated by the computer. There are also several ways to alter the game, like adding more rounds or displaying the score. It’s quite simple and uses the random function to generate a number.
import inquirer from "inquirer";
import chalk from "chalk";
let score = 0;
let running = true;
let User_name = await inquirer.prompt({
    name: "ans",
    type: "input",
    message: chalk.blue.bold("Whats your name? "),
});
console.log(chalk.green.bold(`\n\tWelcome to number gussing game, ${User_name.ans}\n`));
do {
    let random_number = Math.floor(Math.random() * 2 + 1);
    let number_input = await inquirer.prompt({
        name: "ans",
        type: "number",
        message: chalk.red.bold("\nPlease enter number between 1 to 2"),
    });
    if (number_input.ans === random_number) {
        console.log(chalk
            .hex("#c912cc")
            .bold("\n\t😊 congratulation you guess right number🎉"));
        score++;
        console.log(chalk.yellowBright.bold(`\n\t😁 Now your score is: ${score}\n`));
    }
    else {
        console.log(chalk.red.bold("\n\tYou guess wrong number💀"));
        console.log(chalk.red.bold("\n\t😵 Please try again\n"));
    }
    let confirm = await inquirer.prompt({
        name: "ans",
        type: "confirm",
        message: chalk.red.bold("Do you want to continue this game ?"),
    });
    if (confirm.ans === false) {
        running = false;
    }
} while (running);
console.log(chalk.green.bold("\n\t😊 Thank you for playing number gussing game🎉\n"));
